ARG BASE_IMG=ghcr.io/cub-oit-itse/runner:latest
FROM $BASE_IMG AS node-runner

USER root

# https://nodejs.org/en/download/package-manager/#centos-fedora-and-red-hat-enterprise-linux
# 14 is LTS
RUN dnf install -y nodejs20 && \
    dnf clean all

USER $UID
