name: Refresh Images

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 1,16 * *'

jobs:
  refresh_images:
    name: Refresh Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Bump patch release to trigger rebuild
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.REBUILD_PAT }}
          dry_run: true
          default_bump: patch
          tag_prefix: v



